# Generated by Django 3.0.6 on 2020-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('modelis', models.CharField(max_length=200)),
                ('kiekis', models.IntegerField()),
                ('kaina', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('modelis', models.CharField(max_length=200)),
                ('kiekis', models.IntegerField()),
                ('kaina', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('modelis', models.CharField(max_length=200)),
                ('kiekis', models.IntegerField()),
                ('kaina', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
